data: 
  split : 0.3
  training:
    experiment: 7
    metadata_file : train_output.csv
    metadata_file_tile : train_input/train_tile_annotations.csv
    data_dir : train_input/resnet_features/
    save_dir : /data/ubuntu/data/saved_models/experiment_7/
    test_data_dir : test_input/resnet_features


    number_training : 10
    epochs : 230
    lr : 0.0001
    batch_size : 128
    n_monte_carlo : 75
    scheduler : False
    num_workers : 4

    tensorboard:
      use_tensorboard: True
      tensorboard_writer: "/data/ubuntu/data/saved_models/runs/experiment_7"

    saved_model : best_model_7_06.pt
    previous_model : null #/data/ubuntu/data/saved_models/experiment_7/best_model_7_06.pt

submission:
  model_path : "/data/ubuntu/data/saved_models/experiment_7/model1.pt"
  #/data/ubuntu/data/saved_models/experiment_7/model_fold3.pt
  path_csv : /data/ubuntu/data/saved_models/experiment_7/experiment_7_best_model1_.csv