data: 
  split : 0.3
  training:
    experiment: 27
    metadata_file : train_output.csv
    metadata_file_tile : train_input/train_tile_annotations.csv
    data_dir : train_input/resnet_features/
    save_dir : /data/ubuntu/data/saved_models/experiment_27/
    test_data_dir : test_input/resnet_features


    number_training : 5
    epochs : 150
    lr : 0.0001
    batch_size : 32
    n_monte_carlo : 100
    scheduler : False
    num_workers : 2

    tensorboard:
      use_tensorboard: True
      tensorboard_writer: "/data/ubuntu/data/saved_models/runs/experiment_27"

    saved_model : best_model_27_06.pt
    previous_model : null #/data/ubuntu/data/saved_models/experiment_2/best_model_27_06.pt

submission:
  model_path : /data/ubuntu/data/saved_models/experiment_27/model0.pt #/data/ubuntu/data/saved_models/experiment_7/model_fold3.pt
  path_csv : /data/ubuntu/data/saved_models/experiment_27/best_model.csv